/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSecurityAuditRouteImport } from './routes/_authenticated/security-audit'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedActionHistoryRouteImport } from './routes/_authenticated/action-history'
import { Route as ApiPublicApkRouteImport } from './routes/api/public/apk'
import { Route as ApiPublicHooksHourlyAlertsRouteImport } from './routes/api/public/hooks/hourly-alerts'
import { Route as ApiPublicHooksDailySecurityAuditRouteImport } from './routes/api/public/hooks/daily-security-audit'
import { Route as ApiPublicHooksDailyChecksEmailRouteImport } from './routes/api/public/hooks/daily-checks-email'
import { Route as ApiPublicHooksDailyBackupRouteImport } from './routes/api/public/hooks/daily-backup'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityAuditRoute =
  AuthenticatedSecurityAuditRouteImport.update({
    id: '/security-audit',
    path: '/security-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActionHistoryRoute =
  AuthenticatedActionHistoryRouteImport.update({
    id: '/action-history',
    path: '/action-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicApkRoute = ApiPublicApkRouteImport.update({
  id: '/api/public/apk',
  path: '/api/public/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHourlyAlertsRoute =
  ApiPublicHooksHourlyAlertsRouteImport.update({
    id: '/api/public/hooks/hourly-alerts',
    path: '/api/public/hooks/hourly-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySecurityAuditRoute =
  ApiPublicHooksDailySecurityAuditRouteImport.update({
    id: '/api/public/hooks/daily-security-audit',
    path: '/api/public/hooks/daily-security-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyChecksEmailRoute =
  ApiPublicHooksDailyChecksEmailRouteImport.update({
    id: '/api/public/hooks/daily-checks-email',
    path: '/api/public/hooks/daily-checks-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyBackupRoute =
  ApiPublicHooksDailyBackupRouteImport.update({
    id: '/api/public/hooks/daily-backup',
    path: '/api/public/hooks/daily-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/action-history': typeof AuthenticatedActionHistoryRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/daily-checks-email': typeof ApiPublicHooksDailyChecksEmailRoute
  '/api/public/hooks/daily-security-audit': typeof ApiPublicHooksDailySecurityAuditRoute
  '/api/public/hooks/hourly-alerts': typeof ApiPublicHooksHourlyAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/action-history': typeof AuthenticatedActionHistoryRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/daily-checks-email': typeof ApiPublicHooksDailyChecksEmailRoute
  '/api/public/hooks/daily-security-audit': typeof ApiPublicHooksDailySecurityAuditRoute
  '/api/public/hooks/hourly-alerts': typeof ApiPublicHooksHourlyAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/guest': typeof GuestRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/action-history': typeof AuthenticatedActionHistoryRoute
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security-audit': typeof AuthenticatedSecurityAuditRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/hooks/daily-backup': typeof ApiPublicHooksDailyBackupRoute
  '/api/public/hooks/daily-checks-email': typeof ApiPublicHooksDailyChecksEmailRoute
  '/api/public/hooks/daily-security-audit': typeof ApiPublicHooksDailySecurityAuditRoute
  '/api/public/hooks/hourly-alerts': typeof ApiPublicHooksHourlyAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/guest'
    | '/privacy'
    | '/terms'
    | '/action-history'
    | '/admin-settings'
    | '/dashboard'
    | '/reports'
    | '/security-audit'
    | '/settings'
    | '/transactions'
    | '/api/public/apk'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/daily-checks-email'
    | '/api/public/hooks/daily-security-audit'
    | '/api/public/hooks/hourly-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/guest'
    | '/privacy'
    | '/terms'
    | '/action-history'
    | '/admin-settings'
    | '/dashboard'
    | '/reports'
    | '/security-audit'
    | '/settings'
    | '/transactions'
    | '/api/public/apk'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/daily-checks-email'
    | '/api/public/hooks/daily-security-audit'
    | '/api/public/hooks/hourly-alerts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/guest'
    | '/privacy'
    | '/terms'
    | '/_authenticated/action-history'
    | '/_authenticated/admin-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/security-audit'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/api/public/apk'
    | '/api/public/hooks/daily-backup'
    | '/api/public/hooks/daily-checks-email'
    | '/api/public/hooks/daily-security-audit'
    | '/api/public/hooks/hourly-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  GuestRoute: typeof GuestRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicApkRoute: typeof ApiPublicApkRoute
  ApiPublicHooksDailyBackupRoute: typeof ApiPublicHooksDailyBackupRoute
  ApiPublicHooksDailyChecksEmailRoute: typeof ApiPublicHooksDailyChecksEmailRoute
  ApiPublicHooksDailySecurityAuditRoute: typeof ApiPublicHooksDailySecurityAuditRoute
  ApiPublicHooksHourlyAlertsRoute: typeof ApiPublicHooksHourlyAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security-audit': {
      id: '/_authenticated/security-audit'
      path: '/security-audit'
      fullPath: '/security-audit'
      preLoaderRoute: typeof AuthenticatedSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/action-history': {
      id: '/_authenticated/action-history'
      path: '/action-history'
      fullPath: '/action-history'
      preLoaderRoute: typeof AuthenticatedActionHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/apk': {
      id: '/api/public/apk'
      path: '/api/public/apk'
      fullPath: '/api/public/apk'
      preLoaderRoute: typeof ApiPublicApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/hourly-alerts': {
      id: '/api/public/hooks/hourly-alerts'
      path: '/api/public/hooks/hourly-alerts'
      fullPath: '/api/public/hooks/hourly-alerts'
      preLoaderRoute: typeof ApiPublicHooksHourlyAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-security-audit': {
      id: '/api/public/hooks/daily-security-audit'
      path: '/api/public/hooks/daily-security-audit'
      fullPath: '/api/public/hooks/daily-security-audit'
      preLoaderRoute: typeof ApiPublicHooksDailySecurityAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-checks-email': {
      id: '/api/public/hooks/daily-checks-email'
      path: '/api/public/hooks/daily-checks-email'
      fullPath: '/api/public/hooks/daily-checks-email'
      preLoaderRoute: typeof ApiPublicHooksDailyChecksEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-backup': {
      id: '/api/public/hooks/daily-backup'
      path: '/api/public/hooks/daily-backup'
      fullPath: '/api/public/hooks/daily-backup'
      preLoaderRoute: typeof ApiPublicHooksDailyBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActionHistoryRoute: typeof AuthenticatedActionHistoryRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityAuditRoute: typeof AuthenticatedSecurityAuditRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActionHistoryRoute: AuthenticatedActionHistoryRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityAuditRoute: AuthenticatedSecurityAuditRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  GuestRoute: GuestRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicApkRoute: ApiPublicApkRoute,
  ApiPublicHooksDailyBackupRoute: ApiPublicHooksDailyBackupRoute,
  ApiPublicHooksDailyChecksEmailRoute: ApiPublicHooksDailyChecksEmailRoute,
  ApiPublicHooksDailySecurityAuditRoute: ApiPublicHooksDailySecurityAuditRoute,
  ApiPublicHooksHourlyAlertsRoute: ApiPublicHooksHourlyAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
